default:
  mongodb_uri: "mongodb://localhost/meandb"
  sessions_secret: "secret"

development:
  mongodb_uri: "mongodb://localhost/meandb"
  sessions_secret: "secret"

test:
  mongodb_uri: "mongodb://localhost/meandb"
  sessions_secret: "secret"

production:
  mongodb_uri: "mongodb://localhost/meandb"
  sessions_secret: "secret"
